# Generated by Django 3.0.5 on 2021-01-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
