# Generated by Django 3.0.5 on 2021-01-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='created_time',
            new_name='creation_time',
        ),
    ]
