# Generated by Django 3.1.4 on 2021-01-03 01:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210102_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=api.models.generate_unique_id, max_length=8, unique=True),
        ),
    ]
